# 1. Conv Layers

## 1.1 Shapes of Conv Layers

In [3]:
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

# 몇 장을 사용할지 (차원), height, width, channel
N, n_H, n_W, n_C = 1, 28, 28, 1
n_filter = 1
k_size = 3         # filter (kernel) size

images = tf.random.uniform(minval=0, maxval=1,
                           shape=((N, n_H, n_W, n_C)))

print(images.shape)

(1, 28, 28, 1)


In [4]:
conv = Conv2D(filters = n_filter,
              kernel_size = k_size)

# 이미지가 conv 통과한 뒤에 kernel이 초기화 됨
# 이 코드 이후에 weight, bias 불러올 수 있음
y = conv(images)

W, B = conv.get_weights()

print(images.shape)
print(W.shape)  # 3*3 (kernel size) * 1 (channel size), 1 (bias 값 개수)
print(B.shape)
print(y.shape)  # 28 - 3 + 1 = 26

(1, 28, 28, 1)
(3, 3, 1, 1)
(1,)
(1, 26, 26, 1)


### 1.1.1 input의 채널 늘려보기

In [6]:
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 28, 28, 5   # n_C 변경
n_filter = 1
k_size = 3         # filter (kernel) size

images = tf.random.uniform(minval=0, maxval=1,
                           shape=((N, n_H, n_W, n_C)))

conv = Conv2D(filters = n_filter,
              kernel_size = k_size)

y = conv(images)

W, B = conv.get_weights()

print(images.shape)

# 3*3 (kernel size) * 5 (channel size), 1 (bias 값 개수)
# element-wise로 계산하니 결과는 scalar 값 하나가 나옴 = 한 장의 이미지
print(W.shape)

print(B.shape)
print(y.shape)  # 28 - 3 + 1 = 26

(1, 28, 28, 5)
(3, 3, 5, 1)
(1,)
(1, 26, 26, 1)


### 1.1.2 neuron 개수 늘려보기

In [7]:
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 28, 28, 5 
n_filter = 10      # neuron 개수 변경
k_size = 3         # filter (kernel) size

images = tf.random.uniform(minval=0, maxval=1,
                           shape=((N, n_H, n_W, n_C)))

conv = Conv2D(filters = n_filter,
              kernel_size = k_size)

y = conv(images)

W, B = conv.get_weights()

print(images.shape)

# 3*3 (kernel size) * 5 (channel size), 1 (bias 값 개수)
# element-wise로 계산하니 결과는 scalar 값 하나가 나옴 = 한 장의 이미지
print(W.shape)

print(B.shape)
print(y.shape)  # 28 - 3 + 1 = 26

(1, 28, 28, 5)
(3, 3, 5, 10)
(10,)
(1, 26, 26, 10)


In [ ]:
### 1.1.3 input의 image 개수 늘려보기

In [8]:
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

# N : input image 개수 변경
N, n_H, n_W, n_C = 32, 28, 28, 5 
n_filter = 10
k_size = 3         # filter (kernel) size

images = tf.random.uniform(minval=0, maxval=1,
                           shape=((N, n_H, n_W, n_C)))

conv = Conv2D(filters = n_filter,
              kernel_size = k_size)

y = conv(images)

W, B = conv.get_weights()

print(images.shape)

# 3*3 (kernel size) * 5 (channel size), 1 (bias 값 개수)
# element-wise로 계산하니 결과는 scalar 값 하나가 나옴 = 한 장의 이미지
print(W.shape)

print(B.shape)
print(y.shape)  # 28 - 3 + 1 = 26

(32, 28, 28, 5)
(3, 3, 5, 10)
(10,)
(32, 26, 26, 10)


## 1.2 Correlation Calculation

In [17]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 1
n_filter = 1
k_size = 3

images = tf.random.uniform(minval=0, maxval=1,
                           shape=((N, n_H, n_W, n_C)))

conv = Conv2D(filters = n_filter, kernel_size = k_size)

y = conv(images)
print('Y (Tensorflow): ', y.numpy().shape)

# ★ squeeze : shape이 (1, 3, 3, 1)인 경우, 앞뒤 1을 없애줌 = 필요없는 dimension 없애줌
print('Y (Tensorflow): ', y.numpy().squeeze())  # 결과 : 3 * 3

W, B = conv.get_weights()

Y (Tensorflow):  (1, 3, 3, 1)
Y (Tensorflow):  [[-0.23396385  0.7658437   0.10931379]
 [ 0.18021762  0.3420511   0.23813182]
 [ 0.09675416  0.6452862  -0.15992709]]


In [18]:
print(images.shape)
print(W.shape)
print(B.shape)

(1, 5, 5, 1)
(3, 3, 1, 1)
(1,)


In [19]:
images = images.numpy().squeeze()
W = W.squeeze()

print(images.shape)
print(W.shape)
print(B.shape)

(5, 5)
(3, 3)
(1,)


In [23]:
y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1))

for i in range(n_H - k_size + 1):
    for j in range(n_W - k_size + 1):
        # print(i, j)   # 이동하는 window의 첫 번째 index를 잡아줌
        
        window = images[i : i+k_size, j : j+k_size]
        # print(window.shape)
        
        # conv(images) manual 계산
        y_man[i, j] = np.sum(window * W) + B
        
print('Y (Manual): ', y_man)

Y (Manual):  [[-0.23396385  0.76584369  0.10931379]
 [ 0.18021768  0.34205109  0.23813188]
 [ 0.09675419  0.6452862  -0.15992709]]


## 1.3 Correlation with n-Channel

In [27]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

# color image라서 n_C가 3이었다고 가정
N, n_H, n_W, n_C = 1, 5, 5, 3
n_filter = 1
k_size = 3

images = tf.random.uniform(minval=0, maxval=1,
                           shape=((N, n_H, n_W, n_C)))

conv = Conv2D(filters = n_filter, kernel_size = k_size)

y = conv(images)
print('Y (Tensorflow): ', y.numpy().squeeze())

W, B = conv.get_weights()

print(images.shape)
print(W.shape)

images = images.numpy().squeeze()
W = W.squeeze()

print(images.shape)
print(W.shape)

Y (Tensorflow):  [[0.72504264 0.8121899  1.2083075 ]
 [1.162451   0.66338664 1.4295512 ]
 [0.38495976 0.5965969  1.0655301 ]]
(1, 5, 5, 3)
(3, 3, 3, 1)
(5, 5, 3)
(3, 3, 3)


In [28]:
y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1))

for i in range(n_H - k_size + 1):
    for j in range(n_W - k_size + 1):
        
        window = images[i : i+k_size, j : j+k_size, :]  # 이 부분만 n-Channel에 따라 코드 달라짐
        y_man[i, j] = np.sum(window * W) + B   # conv(images) manual 계산
        
print('Y (Manual): ', y_man)

Y (Manual):  [[0.72504276 0.81218988 1.20830762]
 [1.16245103 0.6633867  1.42955124]
 [0.38495994 0.5965969  1.06552994]]


# 2. Conv Layer with Filters

## 2.1 Shapes with Filters

딥러닝에서 어떤 걸 배워도 아래와 같이 검증하는 것에 익숙해져야 함
- 이 때 가장 쉬운 방법은 shape을 따지는 것
- 특히 RNN 처럼 복잡해질수록 shape을 잘 따져줘야 함
- 지금부터 연습 잘 해두기

In [32]:
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 28, 28, 3
n_filter = 5
k_size = 3

images = tf.random.uniform(minval=0, maxval=1,
                           shape=(N, n_H, n_W, n_C))

conv = Conv2D(filters=n_filter, kernel_size=k_size)

Y = conv(images)

W, B = conv.get_weights()

print('Input Image: {}'.format(images.shape))
print('W/B: {} / {}'.format(W.shape, B.shape))
print('Output Image: {}'.format(Y.shape))

Input Image: (1, 28, 28, 3)
W/B: (3, 3, 3, 5) / (5,)
Output Image: (1, 26, 26, 5)


<b>결과 해석</b>
- 3차원 이미지가 input됨 : 28 * 28 * 3
  - window size가 3이니까 '3\*3\*3'인 3차원 window가 만들어짐 
  - window size에 element wise product을 해주려면 kernel size도 '3\*3\*3' size여야 함
    - n_filter 지정에 따라 kernel가 5개가 생김
    - kernel들은 각각 한 장의 이미지를 만들어내니, 총 5개의 사진이 만들어지는 것
- Weight (3, 3, 3, 5) : '3\*3\*3'이 5개가 있다
- Bias (5, ) : kernel마다 bias가 있으니, bias도 5개가 있다
- Output (1, 26, 26, 5) : 28-3+1 = 26 → '26 * 26 * 5'가 1개 (데이터 개수) 만들어짐
  - 데이터 개수는 Dense Layer처럼 계속 바뀌지 않음

## 2.2 Computations with Filters

In [87]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 3
n_filter = 3
k_size = 4   # kernel size는 보통 홀수 값으로 선정하는데, 여기서는 연습삼아 4로 설정
images = tf.random.uniform(minval=0, maxval=1,
                           shape=(N, n_H, n_W, n_C))

# Forward Propagation (Tensorflow)
conv = Conv2D(filters=n_filter, kernel_size=k_size)
Y = conv(images)
print(Y.shape)
print("Y (Tensorflow): \n", Y.numpy())

(1, 2, 2, 3)
Y (Tensorflow): 
 [[[[ 0.38629398  0.35393167 -1.0221311 ]
   [ 0.5403331   0.63368464 -1.1689563 ]]

  [[ 0.16262168  0.13914028 -1.0910604 ]
   [ 0.2339564   0.1160766  -0.4636816 ]]]]


### 2.2.1 squeeze & swapaxes 예시

- 위 Y 차원 구성이 너무 복잡하니까, 아래와 같이 squeeze, swapaxes를 사용해서 간단하게 바꿔볼 수 있음</b>
  - ★ swapaxes : 첫 번째 차원과 마지막 차원을 바꿔줘라

In [88]:
print(Y.numpy().shape)
print(Y.numpy().squeeze().shape)
print(Y.numpy().squeeze().swapaxes(0, -1).shape)

(1, 2, 2, 3)
(2, 2, 3)
(3, 2, 2)


### 2.2.2 좀 더 간단하게 numpy를 활용한 예시

In [89]:
import numpy as np

images = np.random.randint(low=0, high=10, size=(2,3,4))
print(images.shape, '\n', images)

(2, 3, 4) 
 [[[8 0 2 1]
  [5 8 8 8]
  [4 4 0 1]]

 [[2 2 3 5]
  [9 4 4 2]
  [8 9 7 3]]]


채널 별 이미지 보기
- 첫 번째 채널의 이미지 : [[4 4 7] [9 2 1]]
- 두 번째 채널의 이미지 : [[0 0 1] [6 8 0]]
- 세 번째 채널의 이미지 : [[3 1 9] [0 6 5]]
- 네 번째 채널의 이미지 : [[8 6 5] [5 8 6]]

In [90]:
for c in range(4):
    print(images[:, :, c])

[[8 5 4]
 [2 9 8]]
[[0 8 4]
 [2 4 9]]
[[2 8 0]
 [3 4 7]]
[[1 8 1]
 [5 2 3]]


- 원래 image size : (2, 3, 4)
  - 0번째 차원 : 2
  - 1번째 차원 : 3
  - 2번째 차원 : 4
- np.transpose(images, (2, 0, 1))
  - 2번째 차원을 0번째 차원으로 변경
  - 0번째 차원을 1번째 차원으로 변경
  - 1번째 차원을 2번째 차원으로 변경
- 변경 후 size : (4, 2, 3)

In [91]:
tmp = np.transpose(images, (2, 0, 1))
print(tmp.shape)

(4, 2, 3)


위에서 아래 코드 실행했던 것과 동일한 결과 나옴
```python
for c in range(4):
    print(images[:, :, c])
```    

In [92]:
for c in range(4):
    print(tmp[c, :, :])

[[8 5 4]
 [2 9 8]]
[[0 8 4]
 [2 4 9]]
[[2 8 0]
 [3 4 7]]
[[1 8 1]
 [5 2 3]]


### 2.2.3 Transpose 적용하기

In [93]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 3
n_filter = 3
k_size = 4        # kernel size는 보통 홀수 값으로 선정하는데, 여기서는 연습삼아 4로 설정
images = tf.random.uniform(minval=0, maxval=1,
                           shape=(N, n_H, n_W, n_C))

<b>Forward Propagation (Tensorflow)</b>

In [94]:
conv = Conv2D(filters=n_filter, kernel_size=k_size)
Y = conv(images)

Y = np.transpose(Y.numpy().squeeze(), (2, 0, 1))

W, B = conv.get_weights()
print(W.shape, B.shape)

print("\nY (Tensorflow): \n", Y)

(4, 4, 3, 3) (3,)

Y (Tensorflow): 
 [[[ 0.64011157  0.6090236 ]
  [-0.21341035 -0.35040626]]

 [[-0.20548698 -0.28521046]
  [ 0.26701385 -0.00487614]]

 [[ 0.38349116 -0.11999119]
  [ 0.55846655  0.8831266 ]]]


<b>Forward Propagation (Manual)</b>

In [95]:
images = images.numpy().squeeze()

Y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1, n_filter))

# 하나의 채널을 뽑아서 채널마다 filtering을 하는 과정
for c in range(n_filter):
    c_w = W[:, :, :, c]
    c_b = B[c]
    
    # 각 채널을 돌 때마다 weight matrix 생성됨 : (4, 4, 3)
    # print(c_w.shape, c_b.shape)
    
    for h in range(n_H - k_size + 1):
        for w in range(n_W - k_size + 1):
            window = images[h:h+k_size, w:w+k_size, :]
            conv = np.sum(window*c_w) + c_b
            
            Y_man[h, w, c] = conv
            
print(Y_man.shape)

(2, 2, 3)


In [96]:
print("\nY (Manual): \n", np.transpose(Y_man, (2,0,1)))


Y (Manual): 
 [[[ 0.64011168  0.60902363]
  [-0.21341032 -0.35040641]]

 [[-0.20548698 -0.28521046]
  [ 0.26701391 -0.00487623]]

 [[ 0.38349116 -0.11999115]
  [ 0.55846643  0.88312668]]]


# 3. Conv Layers with Activation Functions

In [97]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 3
n_filter = 3
k_size = 4   # kernel size는 보통 홀수 값으로 선정하는데, 여기서는 연습삼아 4로 설정
images = tf.random.uniform(minval=0, maxval=1,
                           shape=(N, n_H, n_W, n_C))

# Forward Propagation (Tensorflow)
conv = Conv2D(filters=n_filter, kernel_size=k_size, activation = 'sigmoid')
Y = conv(images)

Y = np.transpose(Y.numpy().squeeze(), (2, 0, 1))
print("\nY (Tensorflow): \n", Y)

W, B = conv.get_weights()

# Forward Propagation (Manual)
images = images.numpy().squeeze()

Y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1, n_filter))

# 하나의 채널을 뽑아서 채널마다 filtering을 하는 과정
for c in range(n_filter):
    c_w = W[:, :, :, c]
    c_b = B[c]
    
    # 각 채널을 돌 때마다 weight matrix 생성됨 : (4, 4, 3)
    # print(c_w.shape, c_b.shape)
    
    for h in range(n_H - k_size + 1):
        for w in range(n_W - k_size + 1):
            window = images[h:h+k_size, w:w+k_size, :]
            conv = np.sum(window*c_w) + c_b

            # sigmoid 식 적용
            conv = 1/(1 + np.exp(-conv))
            
            Y_man[h, w, c] = conv
            
print("\nY (Manual): \n", np.transpose(Y_man, (2,0,1)))


Y (Tensorflow): 
 [[[0.42501742 0.44087   ]
  [0.5235869  0.4907182 ]]

 [[0.26470178 0.40601736]
  [0.31969726 0.32826   ]]

 [[0.46532708 0.37008804]
  [0.46315348 0.45391896]]]

Y (Manual): 
 [[[0.4250174  0.44087   ]
  [0.52358697 0.49071818]]

 [[0.26470176 0.40601737]
  [0.31969723 0.32825999]]

 [[0.46532708 0.37008801]
  [0.46315348 0.45391896]]]


# 4. Models with Conv Layers

## 4.1 Models with Sequential Method

In [10]:
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D

n_neurons = [10, 20, 30]

model = Sequential()
model.add(Conv2D(filters=n_neurons[0], kernel_size=3, activation='relu')) # 28-3+1 = 26 → 26 * 26 * 10 (n_neurons)
model.add(Conv2D(filters=n_neurons[1], kernel_size=3,activation='relu'))  # 26-3+1 = 24 → 24 * 24 * 20 (n_neurons)
model.add(Conv2D(filters=n_neurons[2], kernel_size=3,activation='relu'))  # 24-3+1 = 22 → 22 * 22 * 30 (n_neurons)

x = tf.random.normal(shape=(32, 28, 28, 3))  # 처음 input : 28 * 28 * 3
predictions = model(x)

print("Input: {}".format(x.shape))
print("Output: {}".format(predictions.shape))

Input: (32, 28, 28, 3)
Output: (32, 22, 22, 30)


In [5]:
for layer in model.layers:
    print(layer)
    
    W, B = layer.get_weights()
    print(W.shape, B.shape)

(3, 3, 3, 10) (10,)
(3, 3, 10, 20) (20,)
(3, 3, 20, 30) (30,)


In [6]:
trainable_variables = model.trainable_variables
print(type(trainable_variables))   # list가 들어있음

<class 'list'>


- trainable_variables 안에 tensor가 들어있는 것 확인
- 또, 위에 W.shape, B.shape과 결과가 같음
- 즉, trainable_variables 안에는 Convolutional Layer에 들어있는 kernel의 weight, bias 등이 있음
- parameter update를 할 때 활용 가능

In [8]:
for train_var in trainable_variables:
    print(type(train_var))
    print(train_var.shape)

<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
(3, 3, 3, 10)
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
(10,)
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
(3, 3, 10, 20)
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
(20,)
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
(3, 3, 20, 30)
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
(30,)


## 4.2 Models with Model Sub-classing

★ 장점 : Model Sub-classing 안에서 method 구현 시 안에서 python의 문법을 그대로 사용하며, 중간 결과 확인 가능
- 중간 중간 print() 함수를 통해 모델 확인
  - ex) print("Input: ", x.shape) 
  - 백만번, 천만번 돌 때 사용하는 게 아니라 prototype을 만들 때
- 중간에 weight, bias 값 받고 확인
  - ex) W, B = conv_layer.get_weights()
  - ex) print("W/B: {}/{}".format(W.shape, B.shape))
- prototype 이후 실제 모델 만들 때는 이 부분을 # 주석처리만 해 주면 됨
  - 연구, 개발 시 매우 유용

### 4.2.1 방법1 : 같은 레이어들을 사용할 때
- for문 사용해서 일괄 적용
```python
for n_neuron in n_neurons:
    self.conv_layers.append(Conv2D(filters=n_neuron, kernel_size=3, activation='relu'))   
```

In [16]:
import tensorflow as tf

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Conv2D

n_neurons = [10, 20, 30]

class TestModel(Model):
    def __init__(self):
        super(TestModel, self).__init__()
        
        global n_neurons        
        
        # 방법1
        self.conv_layers = []
        for n_neuron in n_neurons:
            self.conv_layers.append(Conv2D(filters=n_neuron, kernel_size=3, activation='relu'))        
     
    def call(self, x):
        # print("Input: ", x.shape)        # prototype 생성 시 print를 통해 확인 → 실제 모델 삭제
        
        # print("\n===== Conv Layers =====\n")
        # forward propagation
        for conv_layer in self.conv_layers:
            x = conv_layer(x)
            W, B = conv_layer.get_weights() # weight, bias 값 받기
            # print("W/B: {}/{}".format(W.shape, B.shape)) # prototype 생성 시 print를 통해 확인 → 실제 모델 삭제
            # print("X: {}\n".format(x.shape)) # prototype 생성 시 print를 통해 확인 → 실제 모델 삭제
        return x

model = TestModel()

x = tf.random.normal(shape=(32, 28, 28, 3))  # 처음 input : 28 * 28 * 3
predictions = model(x)

print("Input: {}".format(x.shape))
print("Output: {}".format(predictions.shape))

Input:  (32, 28, 28, 3)

===== Conv Layers =====

W/B: (3, 3, 3, 10)/(10,)
X: (32, 26, 26, 10)

W/B: (3, 3, 10, 20)/(20,)
X: (32, 24, 24, 20)

W/B: (3, 3, 20, 30)/(30,)
X: (32, 22, 22, 30)

Input: (32, 28, 28, 3)
Output: (32, 22, 22, 30)


In [12]:
for layer in model.layers:    
    W, B = layer.get_weights()
    print(W.shape, B.shape)
    
print("==========")

for train_var in trainable_variables:
    print(train_var.shape)

(3, 3, 3, 10) (10,)
(3, 3, 10, 20) (20,)
(3, 3, 20, 30) (30,)
(3, 3, 3, 10)
(10,)
(3, 3, 10, 20)
(20,)
(3, 3, 20, 30)
(30,)


### 4.2.1 방법2 : 다른 레이어들을 사용할 때
- 하나씩 적용해서 자유롭게 activation 등 변경
  - self.conv1 = Conv2D(filters=n_neurons[0], kernel_size=3, activation='relu')
  - self.conv2 = Conv2D(filters=n_neurons[1], kernel_size=3, activation='relu')
  - self.conv3 = Conv2D(filters=n_neurons[2], kernel_size=3, activation='relu')

In [17]:
import tensorflow as tf

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Conv2D

n_neurons = [10, 20, 30]

class TestModel(Model):
    def __init__(self):
        super(TestModel, self).__init__()
        
        global n_neurons        
        
        # 방법2
        self.conv1 = Conv2D(filters=n_neurons[0], kernel_size=3, activation='relu')
        self.conv2 = Conv2D(filters=n_neurons[1], kernel_size=3, activation='relu')
        self.conv3 = Conv2D(filters=n_neurons[2], kernel_size=3, activation='relu')
        
     
    def call(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.conv3(x)
        
        return x