# Parameter Functions

# 1. Affine Functions with 1 Feature

## 1.1 Affine Function

In [1]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

tf.constant
- vector가 아닌 matrix 형태로 생성됨
- ★ tensorflow는 기본적으로 floating point 32bit를 기준으로 작동함
  - 숫자 작성할 때, floating point로 인지하게 하기 위해 반드시 .(dot) 붙이는 습관 들이기

In [2]:
x = tf.constant([[10.]])
print(x.shape)

x = tf.constant([[10.],[20.]])
print(x.shape)

(1, 1)


### 1.1.1 input setting
- ★ x값을 matrix 형태로 만들기

In [4]:
x = tf.constant([[10.]])

### 1.1.2 Affine Function
- ★ units=1 : Affine Function (Dense Layer) 하나 생성
- ★ Dense(units=1)에서 weight, bias 값을 설정하지 않으면, 따로 생성되지 않음 (값이 없는 상태)
  - W, B = dense.get_weights() 로 weight, bias 값 확인해 보려고 하면 Error 발생
- activation
  - Dense(units=1, activation='linear') → Default
    - ★ sigmoid, tanh, relu에서는 output을 위한 추가 보정이 필요하지만, linear는 z 값 자체가 output이 됨
  - Dense(units=1, activation='sigmoid')
  - Dense(units=1, activation='tanh')
  - Dense(units=1, activation='relu')

In [5]:
dense = Dense(units=1)

### 1.1.3 forward propagation + parameter initialization
- x 값을 forward propagation 통과시키기
- Dense(units=1)에서 weight, bias 값을 설정하지 않았기 때문에
  - ★ dense(x)와 같이 x값이 실제로 통과될 때 weight, bias 값 최초 생성됨 : parameter initialization
- input 'x'에 대해 affine function의 'weight', 'bias' 값 대입해서 y값 연산
  - z = x * w + b

In [10]:
y_tf = dense(x)
print(y_tf)

tf.Tensor([[-1.1352742]], shape=(1, 1), dtype=float32)


### 1.1.4 Get weight, bias
- dense 안에 들어있는 weight와 bias 값 확인해 보기
- matrix 형태로 출력됨

In [9]:
W, B = dense.get_weights()
print(W, B)

[[-0.11352742]] [0.]


### 1.1.5 forward propagation (manual)

- tensorflow - linear algebra 함수를 이용해서 직접 계산해 보고, dense(x)의 계산 결과인 'y_tf'와 일치하는지 확인하기 위함
  - dense(x) : z = x * weight + bias
- matmul : X, weight가 matrix 형태이기 때문에 matrix multiplication 이용

In [16]:
y_man = tf.linalg.matmul(x, W) + B
print(y_man)
print(y_tf)

### 1.1.6 Print Results
- x : 1×1 matrix
- W (weight) : 1×1 matrix
- B (bias) : vector

In [20]:
print('===== Input/Weight/Bias =====')
print('x: {}\n{}\n'.format(x.shape, x.numpy()))
print('W: {}\n{}\n'.format(W.shape, W))
print('B: {}\n{}\n'.format(B.shape, B))

print('===== Outputs =====')
print('y (Tensorflow): {}\n{}\n'.format(y_tf.shape, y_tf.shape))
print('y (Manual): {}\n{}\n'.format(y_man.shape, y_man.shape))

===== Input/Weight/Bias =====
x: (1, 1)
[[10.]]

W: (1, 1)
[[-0.11352742]]

B: (1,)
[0.]

===== Outputs =====
y (Tensorflow): (1, 1)
(1, 1)

y (Manual): (1, 1)
(1, 1)



## 1.2 Params Initialization

- linear regression, logistic regression를 배울 때 많이 사용되는 방법
  - 우리가 원하는 weight, bias 값의 방향을 설정하기 위함

In [2]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.initializers import Constant   # 랜덤 값이 아닌 원하는 값으로 initialization 하기 위함

### 1.2.1 input setting

In [3]:
x = tf.constant([[10.]])

### 1.2.2 weight/bias setting

In [23]:
w, b = tf.constant(10.), tf.constant(20.)
print(w, b)

tf.Tensor(10.0, shape=(), dtype=float32) tf.Tensor(20.0, shape=(), dtype=float32)


### 1.2.3 w_init/b_init setting
- layer 안에 있는 weight, bias를 초기화 시켜주기 위한 object
- 실제 tensor 값을 가지고 있는 게 아님

In [24]:
w_init, b_init = Constant(w), Constant(b)
print(w_init, b_init)

<keras.initializers.initializers_v2.Constant object at 0x000001838B68C6D0> <keras.initializers.initializers_v2.Constant object at 0x000001838B606D30>


### 1.2.4 Affine Function

- y_tf : 120. 나옴
  - x (input) = 10, weight = 10, bias = 20
  - 10 * 10 + 20 = 120

In [28]:
dense = Dense(units=1,
              activation='linear',
              kernel_initializer=w_init,
              bias_initializer=b_init)

y_tf = dense(x)
print(y_tf)

tf.Tensor([[120.]], shape=(1, 1), dtype=float32)


weight, bias 값 확인해 보니, 내가 원했던 10.과 20.으로 각각 초기화 되어 있음

In [27]:
W, B = dense.get_weights()

print('W: {}\n{}\n'.format(W.shape, W))
print('B: {}\n{}\n'.format(B.shape, B))

W: (1, 1)
[[10.]]

B: (1,)
[20.]



# 2. Affine Functions with n Features

## 2.1 Affine Functions with n Features

In [29]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

### 2.1.1 input setting
- uniform distribution에서 가져오기
- minval=0, maxval=10 : 0~10까지 숫자 중 선택

In [31]:
x = tf.random.uniform(shape=(1,10), minval=0, maxval=10)
print(x.shape, '\n', x)

(1, 10) 
 tf.Tensor(
[[0.36864758 2.795496   4.4873357  3.2905495  9.087748   6.357126
  8.873041   6.0415316  8.092084   5.4093957 ]], shape=(1, 10), dtype=float32)


### 2.1.2 Affine Function

In [34]:
dense = Dense(units=1)

### 2.1.3 forward propagation

- 위 Dense(units=1) 에서 weight, bias 값 따로 설정 안 해 줬으니
  - dense(x)를 통과하면서 weight, bias 초기화 생성됨
- x 값이 10개가 있으니, ★ weight 10개, bias 1개를 초기화 시켜줌

In [39]:
y_tf = dense(x)

W, B = dense.get_weights()

★ z = x 값의 transpose * W + B

In [40]:
y_man = tf.linalg.matmul(x, W) + B

### 2.1.4 Print Results

- ★ x 값이 10개가 있으니 weight는 10개 값을 가지고 있는 column vector로 생성됨
- bias는 scalar 값 1개

In [38]:
print('===== Input/Weight/Bias =====')
print('x: {}\n{}\n'.format(x.shape, x.numpy()))
print('W: {}\n{}\n'.format(W.shape, W))
print('B: {}\n{}\n'.format(B.shape, B))

print('===== Outputs =====')
print('y (Tensorflow): {}\n{}\n'.format(y_tf.shape, y_tf.shape))
print('y (Manual): {}\n{}\n'.format(y_man.shape, y_man.shape))

===== Input/Weight/Bias =====
x: (1, 10)
[[0.36864758 2.795496   4.4873357  3.2905495  9.087748   6.357126
  8.873041   6.0415316  8.092084   5.4093957 ]]

W: (10, 1)
[[ 0.34909564]
 [ 0.159612  ]
 [ 0.55341536]
 [ 0.14207762]
 [ 0.02079248]
 [-0.6888896 ]
 [-0.20484728]
 [-0.3683192 ]
 [ 0.13245553]
 [-0.11672592]]

B: (1,)
[0.]

===== Outputs =====
y (Tensorflow): (1, 1)
(1, 1)

y (Manual): (1, 1)
(1, 1)



# 3. Activation Functions

## 3.1 Activation Layers

In [4]:
import tensorflow as tf

from tensorflow.math import exp, maximum
from tensorflow.keras.layers import Activation

# input setting
x = tf.random.normal(shape=(1,5))

# activation function
sigmoid = Activation('sigmoid')
tanh = Activation('tanh')
relu = Activation('relu')

# forward propagation - Tensorflow
y_sigmoid_tf = sigmoid(x)
y_tanh_tf = tanh(x)
y_relu_tf = relu(x)

# forward propagation - manual
y_sigmoid_man = 1 / (1 + exp(-x))
y_tanh_man = (exp(x)-exp(-x)) / (exp(x)+exp(-x))
y_relu_man = maximum(x,0)

# print results
print('x: {}\n{}'.format(x.shape, x.numpy()))

print('Sigmoid(Tensorflow): {}\n{}'.format(y_sigmoid_tf.shape, y_sigmoid_tf.numpy()))
print('Sigmoid(manual): {}\n{}'.format(y_sigmoid_man.shape, y_sigmoid_man.numpy()))

print('Tanh(Tensorflow): {}\n{}'.format(y_tanh_tf.shape, y_tanh_tf.numpy()))
print('Tanh(manual): {}\n{}'.format(y_tanh_man.shape, y_tanh_man.numpy()))

print('Relu(Tensorflow): {}\n{}'.format(y_relu_tf.shape, y_relu_tf.numpy()))
print('Relu(manual): {}\n{}'.format(y_relu_man.shape, y_relu_man.numpy()))

## 3.2 Activation in Dense Layer

In [12]:
import tensorflow as tf
from tensorflow.math import exp, maximum
from tensorflow.keras.layers import Dense

### 3.2.1 Input Setting

In [13]:
x = tf.random.normal(shape=(1,5))

### 3.2.2 Artificial Neurons

- Dense Layer에서 affine function을 만들고 그 뒤에 바로 activation function을 통과하도록 구현
- affine function : z = x^T * w + b
  - 현재 input 'x'는 5개 값이 있으니 affine function에서는 weight 5개, bias 1개 생성
- activation function : sigmoid(z), tanh(z), relu(z)

In [16]:
dense_sigmoid = Dense(units=1, activation='sigmoid')
dense_tanh = Dense(units=1, activation='tanh')
dense_relu = Dense(units=1, activation='relu')

### 3.2.3 Forward Propagation : Tensorflow

In [17]:
# Tensorflow
y_sigmoid = dense_sigmoid(x)
y_tanh = dense_tanh(x)
y_relu = dense_relu(x)

# Manual
W, B = dense_sigmoid.get_weights()
z = tf.linalg.matmul(x, W) + B
a = 1 / (1 + exp(-z))

# Tensorflow vs Manual : 결과값 같은지 비교 & 검증
print('Activation value (Tensorflow): {}\n{}'.format(y_sigmoid.shape, y_sigmoid.numpy()))
print('Activation value (manual): {}\n{}'.format(a.shape, a.numpy()))

# Print Results
print('AN with Sigmoid: {}\n{}'.format(y_sigmoid.shape, y_sigmoid.numpy()))
print('AN with Tanh: {}\n{}'.format(y_sigmoid.shape, y_tanh.numpy()))
print('AN with ReLU: {}\n{}'.format(y_sigmoid.shape, y_relu.numpy()))

# 4. Artificial Neurons

## 4.1 Artificial Neurons

- 1~3에서 배운 내용 정리 : 구현부터 검증까지
- 평소 혼자 분석할 때도 이렇게 tensorflow를 사용할 때와 manually 작업했을 때 결과가 같게 나오는지 ★ 검증하기
  - 실제로 내가 배운, 알고 있는 내용이 제대로 구현되고 있는지 확인
  - 이렇게 이해를 하고 있어야 추가적인 연구 개발이 가능함

In [27]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.math import exp, maximum

activation = 'sigmoid'
#activation = 'tanh'
#activation = 'relu'

x = tf.random.uniform(shape=(1,10)) # input setting

dense = Dense(units=1, activation=activation)  # affine + activation function

y_tf = dense(x)
W, B = dense.get_weights()

# calculate activation vaue manually
y_man = tf.linalg.matmul(x, W) + B

if activation == 'sigmoid':
    y_man = 1/(1+exp(-y_man))
elif activation == 'tanh':
    y_man = (exp(y_man) - exp(-y_man)) / (exp(y_man) + exp(-y_man))
elif activation == 'relu':
    y_man = maximum(x, 0)

print('Activation: {}\n'.format(activation))
print('y_tf: {}\n{}\n'.format(y_tf.shape, y_tf.numpy()))
print('y_man: {}\n{}\n'.format(y_man.shape, y_man.numpy()))

Activation: sigmoid

y_tf: (1, 1)
[[0.4292091]]

y_man: (1, 1)
[[0.42920908]]



# 5. Minibatches

## 5.1 Shapes of Dense Layers

- minibatch size 'N'은 절대 weight, bias 크기에 영향을 미치지 않음
- feature size에 따라서만 weight 변화

In [31]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 8, 10                        # set input params
x = tf.random.normal(shape=(N, n_feature))  # generate minibatch

dense = Dense(units=1, activation='relu')   # implement an Artifical Neurons
y = dense(x)                                # forward propagation

W, B = dense.get_weights()                  # get weight/bias

# print results
print('Shape of x: ', x.shape)            # matrix 형태
print('Shape of W: ', W.shape)
print('Shape of B: ', B.shape)

Shape of x:  (8, 10)
Shape of W:  (10, 1)
Shape of B:  (1,)


## 5.2 Output Calculations

In [38]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 8, 10                         # set input params
x = tf.random.normal(shape=(N, n_feature))   # generate minibatch

dense = Dense(units=1, activation='sigmoid') # implement an Artifical Neurons
y_tf = dense(x)                              # forward propagation(Tensorflow)

W, B = dense.get_weights()                   # get weight/bias

y_man = tf.linalg.matmul(x,W) + B            # forward propagation(manual)
y_man = 1/(1+tf.math.exp(-y_man))

# print results
print('Output(Tensorflow): \n', y_tf.numpy())
print('Output(manual)    : \n', y_man.numpy())

Output(Tensorflow): 
 [[0.42787078]
 [0.52452624]
 [0.54379654]
 [0.43149492]
 [0.34651136]
 [0.79414344]
 [0.71111906]
 [0.5163546 ]]
Output(manual)    : 
 [[0.42787075]
 [0.5245262 ]
 [0.54379654]
 [0.43149492]
 [0.34651136]
 [0.7941434 ]
 [0.71111906]
 [0.5163546 ]]


★ math.equal로 비교하는 방법은 비추
- floating point가 짤리기도 하기 때문에, 사실 같은데 다른 것처럼 False 출력

In [39]:
print(tf.math.equal(y_tf, y_man))

tf.Tensor(
[[False]
 [False]
 [ True]
 [ True]
 [ True]
 [False]
 [ True]
 [ True]], shape=(8, 1), dtype=bool)
